[window]
opacity = 0.50


[font]
normal = { family = "Terminess Nerd Font", style = "Regular" }
bold = { family = "Terminess Nerd Font", style = "Bold"}
italic = { family = "Terminess Nerd Font", style = "Italic"}
bold_italic = { family = "Terminess Nerd Font", style = "Bold Italic"}


[cursor]
style = { shape = "Beam", blinking = "Off"}
vi_mode_style = { shape = "Beam", blinking = "Off"}


[terminal]
shell = "/usr/bin/zsh" 
osc52= "CopyPaste"


